version: '3.8'

services:
  api:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    container_name: recipe-api-dev
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=development
    container_name: recipe-frontend-dev
    depends_on:
      - api
    volumes:
      # For development hot reloading
      - ./frontend:/app
      - /app/node_modules

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    container_name: recipe-redis

volumes:
  redis_data: 